package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKuaidi<M extends BaseKuaidi<M>> extends Model<M> implements IBean {

	public void setPosttype(java.lang.String posttype) {
		set("posttype", posttype);
	}

	public java.lang.String getPosttype() {
		return get("posttype");
	}

	public void setPostname(java.lang.String postname) {
		set("postname", postname);
	}

	public java.lang.String getPostname() {
		return get("postname");
	}

	public void setPostlogo(java.lang.String postlogo) {
		set("postlogo", postlogo);
	}

	public java.lang.String getPostlogo() {
		return get("postlogo");
	}

}
