package com.demo.common.model;

import com.demo.common.model.base.BaseKuaidi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kuaidi extends BaseKuaidi<Kuaidi> {
	public static final Kuaidi dao = new Kuaidi();
}
